### PR TITLE
Removed node_modules

### PR DESCRIPTION
**Pull request by ajmeese7**
Now the `node_modules` are installed via GitHub Actions CI and you don't have to worry about adding a lot of bulk to your repository 😄 I tested it on my server and the webhook sent fine, but please do your own testing and let me know if you run across any issues.

### CODE REVIEW

**Comment by thomasbnt** [comment]
Hello, thanks again for your contribution @ajmeese7 ! 🎉🚀

Can we combine these two tasks in one action? Like two jobs for node v16 and the main action.

https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow

**Comment by ajmeese7** [comment]
Can it be done? Absolutely.

I was just keeping the two files separate so it's easier for repository visitors to understand which bits of code they need and which ones are unimportant to their project. That being said, if the users read the documentation it *shouldn't* be an issue.

I'll make another commit if that's the route you want to go, give me a few minutes.

**Comment by ajmeese7** [comment]
Commit has been made @thomasbnt

**Comment by thomasbnt** [comment]
You are awesome! Thanks again for your contribution and optimized the code @ajmeese7 🔥🎉

**Comment by ajmeese7** [comment]
Happy to help 😄

**Pull request merged**
